export const COUNTRIES = [
  {
    label: "Afghanistan",
    alpha2: "AF",
    alpha3: "AFG",
    numeric: "004",
    currency: "AFN",
    phoneCode: "+93",
  },
  {
    label: "Albania",
    alpha2: "AL",
    alpha3: "ALB",
    numeric: "008",
    currency: "ALL",
    phoneCode: "+355",
  },
  {
    label: "Algeria",
    alpha2: "DZ",
    alpha3: "DZA",
    numeric: "012",
    currency: "DZD",
    phoneCode: "+213",
  },
  {
    label: "American Samoa",
    alpha2: "AS",
    alpha3: "ASM",
    numeric: "016",
    currency: "USD",
    phoneCode: "+1-684",
  },
  {
    label: "Andorra",
    alpha2: "AD",
    alpha3: "AND",
    numeric: "020",
    currency: "EUR",
    phoneCode: "+376",
  },
  {
    label: "Angola",
    alpha2: "AO",
    alpha3: "AGO",
    numeric: "024",
    currency: "AOA",
    phoneCode: "+244",
  },
  {
    label: "Anguilla",
    alpha2: "AI",
    alpha3: "AIA",
    numeric: "660",
    currency: "XCD",
    phoneCode: "+1-264",
  },
  {
    label: "Antarctica",
    alpha2: "AQ",
    alpha3: "ATA",
    numeric: "010",
    currency: "",
    phoneCode: "",
  },
  {
    label: "Antigua and Barbuda",
    alpha2: "AG",
    alpha3: "ATG",
    numeric: "028",
    currency: "XCD",
    phoneCode: "+1-268",
  },
  {
    label: "Argentina",
    alpha2: "AR",
    alpha3: "ARG",
    numeric: "032",
    currency: "ARS",
    phoneCode: "+54",
  },
  {
    label: "Armenia",
    alpha2: "AM",
    alpha3: "ARM",
    numeric: "051",
    currency: "AMD",
    phoneCode: "+374",
  },
  {
    label: "Aruba",
    alpha2: "AW",
    alpha3: "ABW",
    numeric: "533",
    currency: "AWG",
    phoneCode: "+297",
  },
  {
    label: "Australia",
    alpha2: "AU",
    alpha3: "AUS",
    numeric: "036",
    currency: "AUD",
    phoneCode: "+61",
  },
  {
    label: "Austria",
    alpha2: "AT",
    alpha3: "AUT",
    numeric: "040",
    currency: "EUR",
    phoneCode: "+43",
  },
  {
    label: "Azerbaijan",
    alpha2: "AZ",
    alpha3: "AZE",
    numeric: "031",
    currency: "AZN",
    phoneCode: "+994",
  },
  {
    label: "Bahamas",
    alpha2: "BS",
    alpha3: "BHS",
    numeric: "044",
    currency: "BSD",
    phoneCode: "+1-242",
  },
  {
    label: "Bahrain",
    alpha2: "BH",
    alpha3: "BHR",
    numeric: "048",
    currency: "BHD",
    phoneCode: "+973",
  },
  {
    label: "Bangladesh",
    alpha2: "BD",
    alpha3: "BGD",
    numeric: "050",
    currency: "BDT",
    phoneCode: "+880",
  },
  {
    label: "Barbados",
    alpha2: "BB",
    alpha3: "BRB",
    numeric: "052",
    currency: "BBD",
    phoneCode: "+1-246",
  },
  {
    label: "Belarus",
    alpha2: "BY",
    alpha3: "BLR",
    numeric: "112",
    currency: "BYN",
    phoneCode: "+375",
  },
  {
    label: "Belgium",
    alpha2: "BE",
    alpha3: "BEL",
    numeric: "056",
    currency: "EUR",
    phoneCode: "+32",
  },
  {
    label: "Belize",
    alpha2: "BZ",
    alpha3: "BLZ",
    numeric: "084",
    currency: "BZD",
    phoneCode: "+501",
  },
  {
    label: "Benin",
    alpha2: "BJ",
    alpha3: "BEN",
    numeric: "204",
    currency: "XOF",
    phoneCode: "+229",
  },
  {
    label: "Bermuda",
    alpha2: "BM",
    alpha3: "BMU",
    numeric: "060",
    currency: "BMD",
    phoneCode: "+1-441",
  },
  {
    label: "Bhutan",
    alpha2: "BT",
    alpha3: "BTN",
    numeric: "064",
    currency: "BTN",
    phoneCode: "+975",
  },
  {
    label: "Bolivia",
    alpha2: "BO",
    alpha3: "BOL",
    numeric: "068",
    currency: "BOB",
    phoneCode: "+591",
  },
  {
    label: "Bosnia and Herzegovina",
    alpha2: "BA",
    alpha3: "BIH",
    numeric: "070",
    currency: "BAM",
    phoneCode: "+387",
  },
  {
    label: "Botswana",
    alpha2: "BW",
    alpha3: "BWA",
    numeric: "072",
    currency: "BWP",
    phoneCode: "+267",
  },
  {
    label: "Brazil",
    alpha2: "BR",
    alpha3: "BRA",
    numeric: "076",
    currency: "BRL",
    phoneCode: "+55",
  },
  {
    label: "Brunei",
    alpha2: "BN",
    alpha3: "BRN",
    numeric: "096",
    currency: "BND",
    phoneCode: "+673",
  },
  {
    label: "Bulgaria",
    alpha2: "BG",
    alpha3: "BGR",
    numeric: "100",
    currency: "BGN",
    phoneCode: "+359",
  },
  {
    label: "Burkina Faso",
    alpha2: "BF",
    alpha3: "BFA",
    numeric: "854",
    currency: "XOF",
    phoneCode: "+226",
  },
  {
    label: "Burundi",
    alpha2: "BI",
    alpha3: "BDI",
    numeric: "108",
    currency: "BIF",
    phoneCode: "+257",
  },
  {
    label: "Cabo Verde",
    alpha2: "CV",
    alpha3: "CPV",
    numeric: "132",
    currency: "CVE",
    phoneCode: "+238",
  },
  {
    label: "Cambodia",
    alpha2: "KH",
    alpha3: "KHM",
    numeric: "116",
    currency: "KHR",
    phoneCode: "+855",
  },
  {
    label: "Cameroon",
    alpha2: "CM",
    alpha3: "CMR",
    numeric: "120",
    currency: "XAF",
    phoneCode: "+237",
  },
  {
    label: "Canada",
    alpha2: "CA",
    alpha3: "CAN",
    numeric: "124",
    currency: "CAD",
    phoneCode: "+1",
  },
  {
    label: "Central African Republic",
    alpha2: "CF",
    alpha3: "CAF",
    numeric: "140",
    currency: "XAF",
    phoneCode: "+236",
  },
  {
    label: "Chad",
    alpha2: "TD",
    alpha3: "TCD",
    numeric: "148",
    currency: "XAF",
    phoneCode: "+235",
  },
  {
    label: "Chile",
    alpha2: "CL",
    alpha3: "CHL",
    numeric: "152",
    currency: "CLP",
    phoneCode: "+56",
  },
  {
    label: "China",
    alpha2: "CN",
    alpha3: "CHN",
    numeric: "156",
    currency: "CNY",
    phoneCode: "+86",
  },
  {
    label: "Colombia",
    alpha2: "CO",
    alpha3: "COL",
    numeric: "170",
    currency: "COP",
    phoneCode: "+57",
  },
  {
    label: "Comoros",
    alpha2: "KM",
    alpha3: "COM",
    numeric: "174",
    currency: "KMF",
    phoneCode: "+269",
  },
  {
    label: "Congo",
    alpha2: "CG",
    alpha3: "COG",
    numeric: "178",
    currency: "XAF",
    phoneCode: "+242",
  },
  {
    label: "Costa Rica",
    alpha2: "CR",
    alpha3: "CRI",
    numeric: "188",
    currency: "CRC",
    phoneCode: "+506",
  },
  {
    label: "Croatia",
    alpha2: "HR",
    alpha3: "HRV",
    numeric: "191",
    currency: "HRK",
    phoneCode: "+385",
  },
  {
    label: "Cuba",
    alpha2: "CU",
    alpha3: "CUB",
    numeric: "192",
    currency: "CUP",
    phoneCode: "+53",
  },
  {
    label: "Cyprus",
    alpha2: "CY",
    alpha3: "CYP",
    numeric: "196",
    currency: "EUR",
    phoneCode: "+357",
  },
  {
    label: "Czechia",
    alpha2: "CZ",
    alpha3: "CZE",
    numeric: "203",
    currency: "CZK",
    phoneCode: "+420",
  },
  {
    label: "Denmark",
    alpha2: "DK",
    alpha3: "DNK",
    numeric: "208",
    currency: "DKK",
    phoneCode: "+45",
  },
  {
    label: "Djibouti",
    alpha2: "DJ",
    alpha3: "DJI",
    numeric: "262",
    currency: "DJF",
    phoneCode: "+253",
  },
  {
    label: "Dominica",
    alpha2: "DM",
    alpha3: "DMA",
    numeric: "212",
    currency: "XCD",
    phoneCode: "+1-767",
  },
  {
    label: "Dominican Republic",
    alpha2: "DO",
    alpha3: "DOM",
    numeric: "214",
    currency: "DOP",
    phoneCode: "+1-809",
  },
  {
    label: "Ecuador",
    alpha2: "EC",
    alpha3: "ECU",
    numeric: "218",
    currency: "USD",
    phoneCode: "+593",
  },
  {
    label: "Egypt",
    alpha2: "EG",
    alpha3: "EGY",
    numeric: "818",
    currency: "EGP",
    phoneCode: "+20",
  },
  {
    label: "El Salvador",
    alpha2: "SV",
    alpha3: "SLV",
    numeric: "222",
    currency: "USD",
    phoneCode: "+503",
  },
  {
    label: "Equatorial Guinea",
    alpha2: "GQ",
    alpha3: "GNQ",
    numeric: "226",
    currency: "XAF",
    phoneCode: "+240",
  },
  {
    label: "Eritrea",
    alpha2: "ER",
    alpha3: "ERI",
    numeric: "232",
    currency: "ERN",
    phoneCode: "+291",
  },
  {
    label: "Estonia",
    alpha2: "EE",
    alpha3: "EST",
    numeric: "233",
    currency: "EUR",
    phoneCode: "+372",
  },
  {
    label: "Eswatini",
    alpha2: "SZ",
    alpha3: "SWZ",
    numeric: "748",
    currency: "SZL",
    phoneCode: "+268",
  },
  {
    label: "Ethiopia",
    alpha2: "ET",
    alpha3: "ETH",
    numeric: "231",
    currency: "ETB",
    phoneCode: "+251",
  },
  {
    label: "Fiji",
    alpha2: "FJ",
    alpha3: "FJI",
    numeric: "242",
    currency: "FJD",
    phoneCode: "+679",
  },
  {
    label: "Finland",
    alpha2: "FI",
    alpha3: "FIN",
    numeric: "246",
    currency: "EUR",
    phoneCode: "+358",
  },
  {
    label: "France",
    alpha2: "FR",
    alpha3: "FRA",
    numeric: "250",
    currency: "EUR",
    phoneCode: "+33",
  },
  {
    label: "Gabon",
    alpha2: "GA",
    alpha3: "GAB",
    numeric: "266",
    currency: "XAF",
    phoneCode: "+241",
  },
  {
    label: "Gambia",
    alpha2: "GM",
    alpha3: "GMB",
    numeric: "270",
    currency: "GMD",
    phoneCode: "+220",
  },
  {
    label: "Georgia",
    alpha2: "GE",
    alpha3: "GEO",
    numeric: "268",
    currency: "GEL",
    phoneCode: "+995",
  },
  {
    label: "Germany",
    alpha2: "DE",
    alpha3: "DEU",
    numeric: "276",
    currency: "EUR",
    phoneCode: "+49",
  },
  {
    label: "Ghana",
    alpha2: "GH",
    alpha3: "GHA",
    numeric: "288",
    currency: "GHS",
    phoneCode: "+233",
  },
  {
    label: "Gibraltar",
    alpha2: "GI",
    alpha3: "GIB",
    numeric: "292",
    currency: "GIP",
    phoneCode: "+350",
  },
  {
    label: "Greece",
    alpha2: "GR",
    alpha3: "GRC",
    numeric: "300",
    currency: "EUR",
    phoneCode: "+30",
  },
  {
    label: "Greenland",
    alpha2: "GL",
    alpha3: "GRL",
    numeric: "304",
    currency: "DKK",
    phoneCode: "+299",
  },
  {
    label: "Grenada",
    alpha2: "GD",
    alpha3: "GRD",
    numeric: "308",
    currency: "XCD",
    phoneCode: "+1-473",
  },
  {
    label: "Guam",
    alpha2: "GU",
    alpha3: "GUM",
    numeric: "316",
    currency: "USD",
    phoneCode: "+1-671",
  },
  {
    label: "Guatemala",
    alpha2: "GT",
    alpha3: "GTM",
    numeric: "320",
    currency: "GTQ",
    phoneCode: "+502",
  },
  {
    label: "Guinea",
    alpha2: "GN",
    alpha3: "GIN",
    numeric: "324",
    currency: "GNF",
    phoneCode: "+224",
  },
  {
    label: "Guinea-Bissau",
    alpha2: "GW",
    alpha3: "GNB",
    numeric: "624",
    currency: "XOF",
    phoneCode: "+245",
  },
  {
    label: "Guyana",
    alpha2: "GY",
    alpha3: "GUY",
    numeric: "328",
    currency: "GYD",
    phoneCode: "+592",
  },
  {
    label: "Haiti",
    alpha2: "HT",
    alpha3: "HTI",
    numeric: "332",
    currency: "HTG",
    phoneCode: "+509",
  },
  {
    label: "Honduras",
    alpha2: "HN",
    alpha3: "HND",
    numeric: "340",
    currency: "HNL",
    phoneCode: "+504",
  },
  {
    label: "Hong Kong",
    alpha2: "HK",
    alpha3: "HKG",
    numeric: "344",
    currency: "HKD",
    phoneCode: "+852",
  },
  {
    label: "Hungary",
    alpha2: "HU",
    alpha3: "HUN",
    numeric: "348",
    currency: "HUF",
    phoneCode: "+36",
  },
  {
    label: "Iceland",
    alpha2: "IS",
    alpha3: "ISL",
    numeric: "352",
    currency: "ISK",
    phoneCode: "+354",
  },
  {
    label: "India",
    alpha2: "IN",
    alpha3: "IND",
    numeric: "356",
    currency: "INR",
    phoneCode: "+91",
  },
  {
    label: "Indonesia",
    alpha2: "ID",
    alpha3: "IDN",
    numeric: "360",
    currency: "IDR",
    phoneCode: "+62",
  },
  {
    label: "Iran",
    alpha2: "IR",
    alpha3: "IRN",
    numeric: "364",
    currency: "IRR",
    phoneCode: "+98",
  },
  {
    label: "Iraq",
    alpha2: "IQ",
    alpha3: "IRQ",
    numeric: "368",
    currency: "IQD",
    phoneCode: "+964",
  },
  {
    label: "Ireland",
    alpha2: "IE",
    alpha3: "IRL",
    numeric: "372",
    currency: "EUR",
    phoneCode: "+353",
  },
  {
    label: "Israel",
    alpha2: "IL",
    alpha3: "ISR",
    numeric: "376",
    currency: "ILS",
    phoneCode: "+972",
  },
  {
    label: "Italy",
    alpha2: "IT",
    alpha3: "ITA",
    numeric: "380",
    currency: "EUR",
    phoneCode: "+39",
  },
  {
    label: "Jamaica",
    alpha2: "JM",
    alpha3: "JAM",
    numeric: "388",
    currency: "JMD",
    phoneCode: "+1-876",
  },
  {
    label: "Japan",
    alpha2: "JP",
    alpha3: "JPN",
    numeric: "392",
    currency: "JPY",
    phoneCode: "+81",
  },
  {
    label: "Jordan",
    alpha2: "JO",
    alpha3: "JOR",
    numeric: "400",
    currency: "JOD",
    phoneCode: "+962",
  },
  {
    label: "Kazakhstan",
    alpha2: "KZ",
    alpha3: "KAZ",
    numeric: "398",
    currency: "KZT",
    phoneCode: "+7",
  },
  {
    label: "Kenya",
    alpha2: "KE",
    alpha3: "KEN",
    numeric: "404",
    currency: "KES",
    phoneCode: "+254",
  },
  {
    label: "Kiribati",
    alpha2: "KI",
    alpha3: "KIR",
    numeric: "296",
    currency: "AUD",
    phoneCode: "+686",
  },
  {
    label: "Korea (the Democratic People's Republic of)",
    alpha2: "KP",
    alpha3: "PRK",
    numeric: "408",
    currency: "KPW",
    phoneCode: "+850",
  },
  {
    label: "Korea (the Republic of)",
    alpha2: "KR",
    alpha3: "KOR",
    numeric: "410",
    currency: "KRW",
    phoneCode: "+82",
  },
  {
    label: "Kuwait",
    alpha2: "KW",
    alpha3: "KWT",
    numeric: "414",
    currency: "KWD",
    phoneCode: "+965",
  },
  {
    label: "Kyrgyzstan",
    alpha2: "KG",
    alpha3: "KGZ",
    numeric: "417",
    currency: "KGS",
    phoneCode: "+996",
  },
  {
    label: "Lao People's Democratic Republic (the)",
    alpha2: "LA",
    alpha3: "LAO",
    numeric: "418",
    currency: "LAK",
    phoneCode: "+856",
  },
  {
    label: "Latvia",
    alpha2: "LV",
    alpha3: "LVA",
    numeric: "428",
    currency: "EUR",
    phoneCode: "+371",
  },
  {
    label: "Lebanon",
    alpha2: "LB",
    alpha3: "LBN",
    numeric: "422",
    currency: "LBP",
    phoneCode: "+961",
  },
  {
    label: "Libya",
    alpha2: "LY",
    alpha3: "LBY",
    numeric: "434",
    currency: "LYD",
    phoneCode: "+218",
  },
  {
    label: "Liechtenstein",
    alpha2: "LI",
    alpha3: "LIE",
    numeric: "438",
    currency: "CHF",
    phoneCode: "+423",
  },
  {
    label: "Lithuania",
    alpha2: "LT",
    alpha3: "LTU",
    numeric: "440",
    currency: "EUR",
    phoneCode: "+370",
  },
  {
    label: "Luxembourg",
    alpha2: "LU",
    alpha3: "LUX",
    numeric: "442",
    currency: "EUR",
    phoneCode: "+352",
  },
  {
    label: "Madagascar",
    alpha2: "MG",
    alpha3: "MDG",
    numeric: "450",
    currency: "MGA",
    phoneCode: "+261",
  },
  {
    label: "Malaysia",
    alpha2: "MY",
    alpha3: "MYS",
    numeric: "458",
    currency: "MYR",
    phoneCode: "+60",
  },
  {
    label: "Maldives",
    alpha2: "MV",
    alpha3: "MDV",
    numeric: "462",
    currency: "MVR",
    phoneCode: "+960",
  },
  {
    label: "Mali",
    alpha2: "ML",
    alpha3: "MLI",
    numeric: "466",
    currency: "XOF",
    phoneCode: "+223",
  },
  {
    label: "Malta",
    alpha2: "MT",
    alpha3: "MLT",
    numeric: "470",
    currency: "EUR",
    phoneCode: "+356",
  },
  {
    label: "Mexico",
    alpha2: "MX",
    alpha3: "MEX",
    numeric: "484",
    currency: "MXN",
    phoneCode: "+52",
  },
  {
    label: "Monaco",
    alpha2: "MC",
    alpha3: "MCO",
    numeric: "492",
    currency: "EUR",
    phoneCode: "+377",
  },
  {
    label: "Mongolia",
    alpha2: "MN",
    alpha3: "MNG",
    numeric: "496",
    currency: "MNT",
    phoneCode: "+976",
  },
  {
    label: "Montenegro",
    alpha2: "ME",
    alpha3: "MNE",
    numeric: "499",
    currency: "EUR",
    phoneCode: "+382",
  },
  {
    label: "Montserrat",
    alpha2: "MS",
    alpha3: "MSR",
    numeric: "500",
    currency: "XCD",
    phoneCode: "+1-664",
  },
  {
    label: "Morocco",
    alpha2: "MA",
    alpha3: "MAR",
    numeric: "504",
    currency: "MAD",
    phoneCode: "+212",
  },
  {
    label: "Mozambique",
    alpha2: "MZ",
    alpha3: "MOZ",
    numeric: "508",
    currency: "MZN",
    phoneCode: "+258",
  },
  {
    label: "Myanmar",
    alpha2: "MM",
    alpha3: "MMR",
    numeric: "104",
    currency: "MMK",
    phoneCode: "+95",
  },
  {
    label: "Namibia",
    alpha2: "NA",
    alpha3: "NAM",
    numeric: "516",
    currency: "NAD",
    phoneCode: "+264",
  },
  {
    label: "Nauru",
    alpha2: "NR",
    alpha3: "NRU",
    numeric: "520",
    currency: "AUD",
    phoneCode: "+674",
  },
  {
    label: "Nepal",
    alpha2: "NP",
    alpha3: "NPL",
    numeric: "524",
    currency: "NPR",
    phoneCode: "+977",
  },
  {
    label: "Netherlands",
    alpha2: "NL",
    alpha3: "NLD",
    numeric: "528",
    currency: "EUR",
    phoneCode: "+31",
  },
  {
    label: "New Caledonia",
    alpha2: "NC",
    alpha3: "NCL",
    numeric: "540",
    currency: "XPF",
    phoneCode: "+687",
  },
  {
    label: "New Zealand",
    alpha2: "NZ",
    alpha3: "NZL",
    numeric: "554",
    currency: "NZD",
    phoneCode: "+64",
  },
  {
    label: "Nicaragua",
    alpha2: "NI",
    alpha3: "NIC",
    numeric: "558",
    currency: "NIO",
    phoneCode: "+505",
  },
  {
    label: "Niger",
    alpha2: "NE",
    alpha3: "NER",
    numeric: "562",
    currency: "XOF",
    phoneCode: "+227",
  },
  {
    label: "Nigeria",
    alpha2: "NG",
    alpha3: "NGA",
    numeric: "566",
    currency: "NGN",
    phoneCode: "+234",
  },
  {
    label: "Niue",
    alpha2: "NU",
    alpha3: "NIU",
    numeric: "570",
    currency: "NZD",
    phoneCode: "+683",
  },
  {
    label: "Norfolk Island",
    alpha2: "NF",
    alpha3: "NFK",
    numeric: "574",
    currency: "AUD",
    phoneCode: "+672",
  },
  {
    label: "Northern Mariana Islands",
    alpha2: "MP",
    alpha3: "MNP",
    numeric: "580",
    currency: "USD",
    phoneCode: "+1-670",
  },
  {
    label: "Norway",
    alpha2: "NO",
    alpha3: "NOR",
    numeric: "578",
    currency: "NOK",
    phoneCode: "+47",
  },
  {
    label: "Oman",
    alpha2: "OM",
    alpha3: "OMN",
    numeric: "512",
    currency: "OMR",
    phoneCode: "+968",
  },
  {
    label: "Pakistan",
    alpha2: "PK",
    alpha3: "PAK",
    numeric: "586",
    currency: "PKR",
    phoneCode: "+92",
  },
  {
    label: "Palau",
    alpha2: "PW",
    alpha3: "PLW",
    numeric: "585",
    currency: "USD",
    phoneCode: "+680",
  },
  {
    label: "Palestine, State of",
    alpha2: "PS",
    alpha3: "PSE",
    numeric: "275",
    currency: "",
    phoneCode: "+970",
  },
  {
    label: "Panama",
    alpha2: "PA",
    alpha3: "PAN",
    numeric: "591",
    currency: "PAB",
    phoneCode: "+507",
  },
  {
    label: "Papua New Guinea",
    alpha2: "PG",
    alpha3: "PNG",
    numeric: "598",
    currency: "PGK",
    phoneCode: "+675",
  },
  {
    label: "Paraguay",
    alpha2: "PY",
    alpha3: "PRY",
    numeric: "600",
    currency: "PYG",
    phoneCode: "+595",
  },
  {
    label: "Peru",
    alpha2: "PE",
    alpha3: "PER",
    numeric: "604",
    currency: "PEN",
    phoneCode: "+51",
  },
  {
    label: "Philippines",
    alpha2: "PH",
    alpha3: "PHL",
    numeric: "608",
    currency: "PHP",
    phoneCode: "+63",
  },
  {
    label: "Pitcairn",
    alpha2: "PN",
    alpha3: "PCN",
    numeric: "612",
    currency: "NZD",
    phoneCode: "+64",
  },
  {
    label: "Poland",
    alpha2: "PL",
    alpha3: "POL",
    numeric: "616",
    currency: "PLN",
    phoneCode: "+48",
  },
  {
    label: "Portugal",
    alpha2: "PT",
    alpha3: "PRT",
    numeric: "620",
    currency: "EUR",
    phoneCode: "+351",
  },
  {
    label: "Puerto Rico",
    alpha2: "PR",
    alpha3: "PRI",
    numeric: "630",
    currency: "USD",
    phoneCode: "+1-787",
  },
  {
    label: "Qatar",
    alpha2: "QA",
    alpha3: "QAT",
    numeric: "634",
    currency: "QAR",
    phoneCode: "+974",
  },
  {
    label: "Republic of North Macedonia",
    alpha2: "MK",
    alpha3: "MKD",
    numeric: "807",
    currency: "MKD",
    phoneCode: "+389",
  },
  {
    label: "Romania",
    alpha2: "RO",
    alpha3: "ROU",
    numeric: "642",
    currency: "RON",
    phoneCode: "+40",
  },
  {
    label: "Russian Federation",
    alpha2: "RU",
    alpha3: "RUS",
    numeric: "643",
    currency: "RUB",
    phoneCode: "+7",
  },
  {
    label: "Rwanda",
    alpha2: "RW",
    alpha3: "RWA",
    numeric: "646",
    currency: "RWF",
    phoneCode: "+250",
  },
  {
    label: "Réunion",
    alpha2: "RE",
    alpha3: "REU",
    numeric: "638",
    currency: "EUR",
    phoneCode: "+262",
  },
  {
    label: "Saint Barthélemy",
    alpha2: "BL",
    alpha3: "BLM",
    numeric: "652",
    currency: "EUR",
    phoneCode: "+590",
  },
  {
    label: "Saint Helena, Ascension and Tristan da Cunha",
    alpha2: "SH",
    alpha3: "SHN",
    numeric: "654",
    currency: "SHP",
    phoneCode: "+290",
  },
  {
    label: "Saint Kitts and Nevis",
    alpha2: "KN",
    alpha3: "KNA",
    numeric: "659",
    currency: "XCD",
    phoneCode: "+1-869",
  },
  {
    label: "Saint Lucia",
    alpha2: "LC",
    alpha3: "LCA",
    numeric: "662",
    currency: "XCD",
    phoneCode: "+1-758",
  },
  {
    label: "Saint Martin (French part)",
    alpha2: "MF",
    alpha3: "MAF",
    numeric: "663",
    currency: "EUR",
    phoneCode: "+590",
  },
  {
    label: "Saint Pierre and Miquelon",
    alpha2: "PM",
    alpha3: "SPM",
    numeric: "666",
    currency: "EUR",
    phoneCode: "+508",
  },
  {
    label: "Saint Vincent and the Grenadines",
    alpha2: "VC",
    alpha3: "VCT",
    numeric: "670",
    currency: "XCD",
    phoneCode: "+1-784",
  },
  {
    label: "Samoa",
    alpha2: "WS",
    alpha3: "WSM",
    numeric: "882",
    currency: "WST",
    phoneCode: "+685",
  },
  {
    label: "San Marino",
    alpha2: "SM",
    alpha3: "SMR",
    numeric: "674",
    currency: "EUR",
    phoneCode: "+378",
  },
  {
    label: "Sao Tome and Principe",
    alpha2: "ST",
    alpha3: "STP",
    numeric: "678",
    currency: "STN",
    phoneCode: "+239",
  },
  {
    label: "Saudi Arabia",
    alpha2: "SA",
    alpha3: "SAU",
    numeric: "682",
    currency: "SAR",
    phoneCode: "+966",
  },
  {
    label: "Senegal",
    alpha2: "SN",
    alpha3: "SEN",
    numeric: "686",
    currency: "XOF",
    phoneCode: "+221",
  },
  {
    label: "Serbia",
    alpha2: "RS",
    alpha3: "SRB",
    numeric: "688",
    currency: "RSD",
    phoneCode: "+381",
  },
  {
    label: "Seychelles",
    alpha2: "SC",
    alpha3: "SYC",
    numeric: "690",
    currency: "SCR",
    phoneCode: "+248",
  },
  {
    label: "Sierra Leone",
    alpha2: "SL",
    alpha3: "SLE",
    numeric: "694",
    currency: "SLL",
    phoneCode: "+232",
  },
  {
    label: "Singapore",
    alpha2: "SG",
    alpha3: "SGP",
    numeric: "702",
    currency: "SGD",
    phoneCode: "+65",
  },
  {
    label: "Sint Maarten (Dutch part)",
    alpha2: "SX",
    alpha3: "SXM",
    numeric: "534",
    currency: "ANG",
    phoneCode: "+1-721",
  },
  {
    label: "Slovakia",
    alpha2: "SK",
    alpha3: "SVK",
    numeric: "703",
    currency: "EUR",
    phoneCode: "+421",
  },
  {
    label: "Slovenia",
    alpha2: "SI",
    alpha3: "SVN",
    numeric: "705",
    currency: "EUR",
    phoneCode: "+386",
  },
  {
    label: "Solomon Islands",
    alpha2: "SB",
    alpha3: "SLB",
    numeric: "090",
    currency: "SBD",
    phoneCode: "+677",
  },
  {
    label: "Somalia",
    alpha2: "SO",
    alpha3: "SOM",
    numeric: "706",
    currency: "SOS",
    phoneCode: "+252",
  },
  {
    label: "South Africa",
    alpha2: "ZA",
    alpha3: "ZAF",
    numeric: "710",
    currency: "ZAR",
    phoneCode: "+27",
  },
  {
    label: "South Georgia and the South Sandwich Islands",
    alpha2: "GS",
    alpha3: "SGS",
    numeric: "239",
    currency: "GBP",
    phoneCode: "+500",
  },
  {
    label: "South Sudan",
    alpha2: "SS",
    alpha3: "SSD",
    numeric: "728",
    currency: "SSP",
    phoneCode: "+211",
  },
  {
    label: "Spain",
    alpha2: "ES",
    alpha3: "ESP",
    numeric: "724",
    currency: "EUR",
    phoneCode: "+34",
  },
  {
    label: "Sri Lanka",
    alpha2: "LK",
    alpha3: "LKA",
    numeric: "144",
    currency: "LKR",
    phoneCode: "+94",
  },
  {
    label: "Sudan",
    alpha2: "SD",
    alpha3: "SDN",
    numeric: "729",
    currency: "SDG",
    phoneCode: "+249",
  },
  {
    label: "Suriname",
    alpha2: "SR",
    alpha3: "SUR",
    numeric: "740",
    currency: "SRD",
    phoneCode: "+597",
  },
  {
    label: "Svalbard and Jan Mayen",
    alpha2: "SJ",
    alpha3: "SJM",
    numeric: "744",
    currency: "NOK",
    phoneCode: "+47",
  },
  {
    label: "Sweden",
    alpha2: "SE",
    alpha3: "SWE",
    numeric: "752",
    currency: "SEK",
    phoneCode: "+46",
  },
  {
    label: "Switzerland",
    alpha2: "CH",
    alpha3: "CHE",
    numeric: "756",
    currency: "CHF",
    phoneCode: "+41",
  },
  {
    label: "Syrian Arab Republic",
    alpha2: "SY",
    alpha3: "SYR",
    numeric: "760",
    currency: "SYP",
    phoneCode: "+963",
  },
  {
    label: "Taiwan",
    alpha2: "TW",
    alpha3: "TWN",
    numeric: "158",
    currency: "TWD",
    phoneCode: "+886",
  },
  {
    label: "Tajikistan",
    alpha2: "TJ",
    alpha3: "TJK",
    numeric: "762",
    currency: "TJS",
    phoneCode: "+992",
  },
  {
    label: "Tanzania",
    alpha2: "TZ",
    alpha3: "TZA",
    numeric: "834",
    currency: "TZS",
    phoneCode: "+255",
  },
  {
    label: "Thailand",
    alpha2: "TH",
    alpha3: "THA",
    numeric: "764",
    currency: "THB",
    phoneCode: "+66",
  },
  {
    label: "Timor-Leste",
    alpha2: "TL",
    alpha3: "TLS",
    numeric: "626",
    currency: "USD",
    phoneCode: "+670",
  },
  {
    label: "Togo",
    alpha2: "TG",
    alpha3: "TGO",
    numeric: "768",
    currency: "XOF",
    phoneCode: "+228",
  },
  {
    label: "Tokelau",
    alpha2: "TK",
    alpha3: "TKL",
    numeric: "772",
    currency: "NZD",
    phoneCode: "+690",
  },
  {
    label: "Tonga",
    alpha2: "TO",
    alpha3: "TON",
    numeric: "776",
    currency: "TOP",
    phoneCode: "+676",
  },
  {
    label: "Trinidad and Tobago",
    alpha2: "TT",
    alpha3: "TTO",
    numeric: "780",
    currency: "TTD",
    phoneCode: "+1-868",
  },
  {
    label: "Tunisia",
    alpha2: "TN",
    alpha3: "TUN",
    numeric: "788",
    currency: "TND",
    phoneCode: "+216",
  },
  {
    label: "Turkey",
    alpha2: "TR",
    alpha3: "TUR",
    numeric: "792",
    currency: "TRY",
    phoneCode: "+90",
  },
  {
    label: "Turkmenistan",
    alpha2: "TM",
    alpha3: "TKM",
    numeric: "795",
    currency: "TMT",
    phoneCode: "+993",
  },
  {
    label: "Turks and Caicos Islands",
    alpha2: "TC",
    alpha3: "TCA",
    numeric: "796",
    currency: "USD",
    phoneCode: "+1-649",
  },
  {
    label: "Tuvalu",
    alpha2: "TV",
    alpha3: "TUV",
    numeric: "798",
    currency: "AUD",
    phoneCode: "+688",
  },
  {
    label: "Uganda",
    alpha2: "UG",
    alpha3: "UGA",
    numeric: "800",
    currency: "UGX",
    phoneCode: "+256",
  },
  {
    label: "Ukraine",
    alpha2: "UA",
    alpha3: "UKR",
    numeric: "804",
    currency: "UAH",
    phoneCode: "+380",
  },
  {
    label: "United Arab Emirates",
    alpha2: "AE",
    alpha3: "ARE",
    numeric: "784",
    currency: "AED",
    phoneCode: "+971",
  },
  {
    label: "United Kingdom of Great Britain and Northern Ireland",
    alpha2: "GB",
    alpha3: "GBR",
    numeric: "826",
    currency: "GBP",
    phoneCode: "+44",
  },
  {
    label: "United States Minor Outlying Islands",
    alpha2: "UM",
    alpha3: "UMI",
    numeric: "581",
    currency: "USD",
    phoneCode: "+1",
  },
  {
    label: "United States of America",
    alpha2: "US",
    alpha3: "USA",
    numeric: "840",
    currency: "USD",
    phoneCode: "+1",
  },
  {
    label: "Uruguay",
    alpha2: "UY",
    alpha3: "URY",
    numeric: "858",
    currency: "UYU",
    phoneCode: "+598",
  },
  {
    label: "Uzbekistan",
    alpha2: "UZ",
    alpha3: "UZB",
    numeric: "860",
    phoneCode: "+998",
    currency: "UZS",
  },
  {
    label: "Vanuatu",
    alpha2: "VU",
    alpha3: "VUT",
    numeric: "548",
    phoneCode: "+678",
    currency: "VUV",
  },
  {
    label: "Venezuela (Bolivarian Republic of)",
    alpha2: "VE",
    alpha3: "VEN",
    numeric: "862",
    phoneCode: "+58",
    currency: "VES",
  },
  {
    label: "Viet Nam",
    alpha2: "VN",
    alpha3: "VNM",
    numeric: "704",
    phoneCode: "+84",
    currency: "VND",
  },
  {
    label: "Virgin Islands (British)",
    alpha2: "VG",
    alpha3: "VGB",
    numeric: "092",
    phoneCode: "+1-284",
    currency: "USD",
  },
  {
    label: "Virgin Islands (U.S.)",
    alpha2: "VI",
    alpha3: "VIR",
    numeric: "850",
    phoneCode: "+1-340",
    currency: "USD",
  },
  {
    label: "Wallis and Futuna",
    alpha2: "WF",
    alpha3: "WLF",
    numeric: "876",
    phoneCode: "+681",
    currency: "XPF",
  },
  {
    label: "Western Sahara",
    alpha2: "EH",
    alpha3: "ESH",
    numeric: "732",
    phoneCode: "+212",
    currency: "MAD",
  },
  {
    label: "Yemen",
    alpha2: "YE",
    alpha3: "YEM",
    numeric: "887",
    phoneCode: "+967",
    currency: "YER",
  },
  {
    label: "Zambia",
    alpha2: "ZM",
    alpha3: "ZMB",
    numeric: "894",
    phoneCode: "+260",
    currency: "ZMW",
  },
  {
    label: "Zimbabwe",
    alpha2: "ZW",
    alpha3: "ZWE",
    numeric: "716",
    phoneCode: "+263",
    currency: "ZWL",
  },
  {
    label: "Åland Islands",
    alpha2: "AX",
    alpha3: "ALA",
    numeric: "248",
    phoneCode: "+358",
    currency: "EUR",
  },
];
